config/routes.rb
Rails.application.routes.draw do
  root :to => "articles#index"
  get 'login' => "host#login_form"
  post "login" => "host#login"
  post "logout" => "host#logout"
  get "articles/setting" => "articles#setting"
  get 'tags/:tag', to: 'articles#index', as: :tag #追加
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
    mount_uploader :image, ImageUploader
    acts_as_taggable_on :skills
    
end

app/models/host.rb
class Host < ApplicationRecord
    has_secure_password
    validates :login_id, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user,:get_tag

    def set_current_user
        @current_user = Host.find_by(login_id: session[:login_id])
    end

    def get_tag
        @tags = ActsAsTaggableOn::Tag.all
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_host, only: [:setting, :edit, :update, :destroy, :newe]
  before_action :check_user_agent_for_mobile

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles= Article.tagged_with(params[:tag]).page params[:page]
    else
      @articles = Article.page params[:page]
    end
  end

  

  def check_user_agent_for_mobile
    ua = request.user_agent
    if(ua.include?('Mobile') || ua.include?('Android'))
      @mobile = true
    end
  end

  def setting
    @articles = Article.all
  end

  def authenticate_host
    if @current_user == nil
      redirect_to("/login")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to "/articles/setting", notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title,:content,:tag,:image,:heading,:name, :skill_list)
    end

  
end

app/controllers/host_controller.rb
class HostController < ApplicationController
  def login_form
  end

  def login
    @host= Host.find_by(login_id: params[:login_id])
    if @host
      session[:login_id] = @host.login_id
      flash[:notice] = "login success"
      redirect_to("/articles")
    else 
      @error_message = "IDまたはパスワードが違います"
      @login_id = params[:login_id]
      render("host/login_form")
    end
  end

  def logout
    session[:login_id] = nil
    flash[:notice] = "logout success"
    redirect_to("/login")
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/host_helper.rb
module HostHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

</figure>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :image %>
  <%= form.file_field :image %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :skill_list, 'タグをカンマ区切りで入力' %><br/>
    <%= text_field_tag 'article[skill_list]', article.skill_list.join(',') %>
  </div>

  <div class="field">
    <%= form.label :heading%>
    <%= form.text_field :heading %>
  </div>


  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>


<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<% if params[:tag]%>
  <div class="card-panel">
    <h6>タグ：<%= params[:tag]%></h6>
  </div>
<%end%>

<% @articles.each do |article| %>
  <div class="low">
    <div class="card darken-1">
      <div class="card-content">
        <span class="card-title"><%= link_to(article.title,article,method: "get",class: "title_link") %></span>
        <% article.skill_list.each do |tag|%>
          <%= link_to( tag, tag_path(tag),method: "get",class: "btn-flat right title_link")%>
        <% end %>
        <br>
        <br>
        <p><%= article.heading %></p>
      </div>
      <% if article.image != nil%>
        <div class="card-content">
          <div class="container">
            <div class="row">
              <%= image_tag(article.image.url,class: "col s12 center") %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="card-action">
        <%= link_to( 'Show more', article,method: "get",class: "waves-effect waves-light btn-small amber accent-2")%>
      </div>
    </div>
  </div>
  <br>
<% end %>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/setting.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= link_to 'Show', article %></td>
                <td><%= link_to 'Edit', edit_article_path(article) %></td>
                <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
<%= link_to("logout", "/logout", {method: :post}) %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card-panel">
  <h6><%= @article.title %></h6>
  <p class="right-align"><%= @article.created_at %></p>
  <br>
  <%= @article.content %>
</div>

<%= link_to( 'Back', articles_path,method: "get",class: "waves-effect waves-light btn-small amber accent-2" )%>

app/views/host/login_form.html.erb
<div class="main users-new">
    <div class="container">
        <div class="form-heading">ログイン</div>
        <div class="form users-form">
            <div class="form-body">
                <% if @error_message %>
                    <div class="form-error">
                        <%= @error_message %>
                    </div>
                <% end %>
                <%= form_tag("/login") do %>
                    <p>ID</p>
                    <input name="login_id" value="<%= @login_id %>">
                    <p>パスワード</p>
                    <input name="password" type="password" value="<%= @password %>">
                    <input type="submit" value="ログイン">
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <nav class="amber darken-4" >
      <div class="nav-wrapper">
        <%= link_to("nekuralog","/",class: "brand-logo center waves-effect waves-light",method: "get")%>
        <a href="#" data-target="slide-out" class="sidenav-trigger btn-flat waves-effect waves-light"><i class="material-icons">menu</i></a>
      </div>
      <ul id="slide-out" class="sidenav">
        <li class=" amber darken-4">&emsp;tags</li>
        <% @tags.each do |tag| %>
          <li><%= link_to( tag.name+"("+tag.taggings_count.to_s+")", tag_path(tag.name),method: "get",class: "title_link")%></li>
        <%end%>
        <li class=" amber darken-4">&emsp;link</li>
        <li><%= link_to("github","https://github.com/",method: "get",class: "title_link")%></li>
        <li><%= link_to("twitter","https://twitter.com/",method: "get",class: "title_link")%></li>
        <li><%= link_to("admin","/articles/setting",method: "get",class: "title_link")%></li>
      </ul>
    </nav>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <% if @mobile %>
        <div class="col s12">
      <% else %>
        <div class="col s9">
      <% end %>
      <%= yield %>
    </div>
      <ul class="hide-on-small-only">
        <div class="col s3">
          <div class="card">
            <div class="card-image">
              <%= image_tag 'icon.jpeg' %>
            </div>
            <li>author:にーくら</li>
            <li>東京で大学生をしてる。</li>
          </div>
          <div class="card-panel">
            <span class="card-title">tags</span>
            <br>
            <div class="card-content">
              <% @tags.each do |tag| %>
                <li><%= link_to( tag.name+"("+tag.taggings_count.to_s+")", tag_path(tag.name),method: "get",class: "tag_link")%></li>
              <%end%>
            </div>
          </div>
          <div class="card-panel">
            <span class="card-title">links</span>
            <br>
            <li><%= link_to("github","https://github.com/",method: "get",class: "tag_link")%></li>
            <li><%= link_to("twitter","https://twitter.com/",method: "get",class: "tag_link")%></li>
            <li><%= link_to("admin","/articles/setting",method: "get",class: "tag_link")%></li>
          </div>
        </div>
      </ul>
    </div>
  </div>
  </body>
</html>